import React, { useEffect, useState } from 'react';
import { Loader2, Shield, UserPlus, Users } from 'lucide-react';
import { supabase } from '@/lib/customSupabaseClient';
import { ROLE_PRESETS } from '@/lib/dashboardPermissions';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { useToast } from '@/components/ui/use-toast';

const TeamManager = () => {
  const [members, setMembers] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [form, setForm] = useState({ name: '', email: '', password: '', role: 'blog_manager' }); const { toast } = useToast();
  const load = async () => { setLoading(true); const { data, error } = await supabase.from('dashboard_members').select('*').order('created_at', { ascending: false }); if (!error) setMembers(data || []); setLoading(false); };
  useEffect(() => { load(); }, []);
  const createMember = async (event) => { event.preventDefault(); if (form.password.length < 8) return toast({ title: 'Mot de passe trop court', description: 'Utilisez au moins 8 caractères.', variant: 'destructive' }); setSaving(true); const { data, error } = await supabase.functions.invoke('manage-dashboard-user', { body: { action: 'create', ...form, permissions: ROLE_PRESETS[form.role].permissions } }); setSaving(false); if (error || data?.error) return toast({ title: 'Création impossible', description: data?.error || error.message, variant: 'destructive' }); setForm({ name: '', email: '', password: '', role: 'blog_manager' }); toast({ title: 'Collaborateur ajouté', description: 'Il peut maintenant se connecter avec les accès définis.' }); load(); };
  const toggleMember = async (member) => { const { data, error } = await supabase.functions.invoke('manage-dashboard-user', { body: { action: 'toggle', userId: member.user_id, isActive: !member.is_active } }); if (error || data?.error) return toast({ title: 'Modification impossible', description: data?.error || error.message, variant: 'destructive' }); load(); };
  return <div className="space-y-7"><div className="rounded-2xl bg-blue-50 p-5"><div className="flex items-center gap-3"><span className="rounded-xl bg-[#0b1739] p-3 text-white"><Users className="h-5 w-5" /></span><div><h2 className="text-2xl font-bold">Équipe et droits d’accès</h2><p className="text-sm text-slate-600">Créez des comptes limités. Un gestionnaire du blog ne voit et ne modifie que les actualités.</p></div></div></div>
  <div className="grid gap-7 xl:grid-cols-[0.85fr_1.15fr]"><form onSubmit={createMember} className="space-y-5 rounded-2xl border border-slate-200 p-5 md:p-7"><div><h3 className="flex items-center font-bold"><UserPlus className="mr-2 h-5 w-5 text-blue-800" /> Ajouter un collaborateur</h3><p className="mt-1 text-xs text-slate-500">L’adresse e-mail servira à se connecter au tableau de bord.</p></div><div><Label>Nom complet</Label><Input className="mt-2" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></div><div><Label>Adresse e-mail</Label><Input className="mt-2" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /></div><div><Label>Mot de passe provisoire</Label><Input className="mt-2" type="password" minLength={8} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} required /><p className="mt-1 text-xs text-slate-400">Au moins 8 caractères. Communiquez-le au collaborateur de façon sécurisée.</p></div><div><Label>Rôle et autorisations</Label><Select value={form.role} onValueChange={(role) => setForm({ ...form, role })}><SelectTrigger className="mt-2"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(ROLE_PRESETS).map(([id, role]) => <SelectItem key={id} value={id}>{role.label}</SelectItem>)}</SelectContent></Select><div className="mt-3 rounded-xl bg-slate-50 p-3 text-xs text-slate-600"><Shield className="mr-1 inline h-3.5 w-3.5" />Accès : {ROLE_PRESETS[form.role].permissions.join(', ')}</div></div><Button type="submit" disabled={saving} className="w-full bg-[#0b1739] text-white">{saving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <UserPlus className="mr-2 h-4 w-4" />} Créer le compte</Button></form>
  <section className="rounded-2xl border border-slate-200 p-5 md:p-7"><h3 className="font-bold">Collaborateurs</h3><p className="mt-1 text-xs text-slate-500">Désactiver un compte bloque immédiatement ses prochaines connexions.</p>{loading ? <Loader2 className="mx-auto my-16 h-7 w-7 animate-spin" /> : <div className="mt-5 space-y-3">{members.length === 0 && <p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">Aucun collaborateur ajouté.</p>}{members.map((member) => <div key={member.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-4"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-100 font-bold text-blue-900">{(member.name || member.email)[0].toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{member.name || 'Collaborateur'}</p><p className="truncate text-xs text-slate-500">{member.email}</p><p className="mt-1 text-xs font-medium text-blue-700">{ROLE_PRESETS[member.role]?.label || member.role}</p></div><div className="text-right"><Switch checked={member.is_active} onCheckedChange={() => toggleMember(member)} /><p className="mt-1 text-[10px] text-slate-400">{member.is_active ? 'Actif' : 'Bloqué'}</p></div></div>)}</div>}</section></div></div>;
};
export default TeamManager;
